---
title: "R Notebook"
output: html_notebook
---

```{r}
 # Estimacion de la sobrevida va Kaplan-Meier (EKM)
 t<-c(65,100,134,16,121,4,39,56,26,22,1,1,5,65,140,106,121)
 cen<-c(rep(1,14),rep(0,3))
 cgb<-c(2.3,0.75,4.3,2.6,6.0,10.5,10.0,17.0,5.4,7.0,9.4,32.0,35.0,100.0,100.0,52.0,100.0)
 datos<-cbind(t,cen,cgb)
 require(survival)
 datos<-as.data.frame(datos)
 i<-order(datos$t)
 datos<-datos[i,]
 ekm<-survfit(Surv(datos$t,datos$cen)~1)
 st<-ekm$surv
 tekm<-ekm$time
 inv_Phi<-qnorm(st) ### to build the lognormal
 # Graficas de probabilidad
 par(mfrow=c(1,3))
 plot(tekm, -log(st),pch=16,xlab="Tiempo",sub="Exponencial", ylab="-log(S(t))")
 abline(lm(-log(st)~tekm))
 plot(log(tekm),log(-log(st)),pch=16,xlab="log(tiempo)",sub="Weibull",ylab="log(-log(S(t))")
 abline(lm(log(-log(st))~log(tekm)))
 plot(log(tekm),inv_Phi,pch=16,xlab="log(tiempo)",sub="log-normal",ylab=expression(Phi^-1 * (S(t))))
 abline(lm(inv_Phi~log(tekm)))
```

```{r}
reg_exp<-survreg(Surv(datos$t, datos$cen)~datos$cgb, dist='exponential')

reg_weibull<-survreg(Surv(datos$t, datos$cen)~datos$cgb, dist='weibull')

alpha<-1/reg_weibull$scale


reg_lognormal<-survreg(Surv(datos$t, datos$cen)~datos$cgb,dist='lognormal')

```



```{r}

t<-c(65,100,134,16,121,4,39,56,26,22,1,1,5,65,140,106,121,56,65,17,7,16,22,3,4,2,3,8,4,3,30,4,43)
cen<-c(rep(1,14),rep(0,3),rep(1,16))
cgb<-c(2.3,0.75,4.3,2.6,6.0,10.5,10.0,17.0,5.4,7.0,9.4,32.0,35.0,100.0,100.0,52.0,100.0,4.4,3.0,4.0,1.5,9.0,5.3,10.0,19.0,27.0,28.0,31.0,26.0,21.0,79.0,100.0,100.0)
AG<-c(rep(0,17),rep(1,16))

```

```{r}

km.model <- survfit(Surv(t,cen) ~ AG)
st<-km.model$surv
tekm<-km.model$time
plot(tekm, -log(st),pch=16,xlab="Tiempo",sub="Exponencial", ylab="-log(S(t))", col=c("red", "blue"), lwd = 2, las=1)

```



```{r}

t<-c(65,100,134,16,121,4,39,56,26,22,1,1,5,65,140,106,121)
t2<-c(56,65,17,7,16,22,3,4,2,3,8,4,3,30,4,43)

cen1<-c(rep(1,14),rep(0,3))
cen2 <- rep(1,16)
AG0<-rep(0,17)
AG1 <- rep(1,16)

cgb1 <- c(2.3,4.3,2.6,6.0,10.0,17.0,5.4,9.4,32.0,
35.0,100.0,100.0,52.0,100.0,0.75,10.5,7.0)

cgb2 <- c(4.4,3.0,4.0,1.5,9.0,5.3,10.0,19.0,27.0,28.0,31.0,26.0,21.0,79.0,100.0,100.0)

km.AG0<- survfit(Surv(t,cen1)~1)

st0<-km.AG0$surv
tekm0<-km.AG0$time

km.AG1 <- survfit(Surv(t2,cen2)~1)

st1<-km.AG1$surv
tekm1<-km.AG1$time


t <- c(t,t2)
cen <- c(cen1, cen2)
AG <- c(AG0, AG1)



cgb <- c(cgb1,cgb2)

```

```{r}

m<-(cbind(t,cen,AG,cgb))

```


```{r}
reg_weibull<-survreg(Surv(datos$t, datos$cen)~datos$cgb,dist='weibull')
reg_weibull
alpha<-1/reg_weibull$scale
alpha
reg_weibull$loglik
```
```{r}

reg_exp<-survreg(Surv(datos$t, datos$cen)~datos$cgb,
dist='exponential')
reg_exp$loglik

print("--------------------------------------------------------")
reg_weibull<-survreg(Surv(datos$t, datos$cen)~datos$cgb,
dist='weibull')
reg_weibull$loglik
alpha<-1/reg_weibull$scale
alpha

print("--------------------------------------------------------")
reg_lognormal<-survreg(Surv(datos$t, datos$cen)~datos$cgb,
dist='lognormal')
reg_lognormal$loglik

```

```{r}
reg_exp1<-survreg(Surv(t, cen)~1, dist='exponential')
reg_exp1
reg_exp1$loglik

print("--------------------------------------------------------")
reg_exp2<-survreg(Surv(t, cen)~cgb, dist='exponential')
reg_exp2
reg_exp2$loglik
print("--------------------------------------------------------")
reg_exp3<-survreg(Surv(t, cen)~AG, dist='exponential')
reg_exp3
reg_exp3$loglik
print("--------------------------------------------------------")
reg_exp4<-survreg(Surv(t, cen)~cgb+AG, dist='exponential')
reg_exp4
reg_exp4$loglik
print("--------------------------------------------------------")
reg_exp5<-survreg(Surv(t, cen)~cgb+AG+cgb*AG, dist='exponential')
reg_exp5
reg_exp5$loglik
```

