---
title: "R Notebook"
output: html_notebook
---
```{r}
library("survival")
```


```{r}
time <- c(6,6,6,6,7,9,10,10,11,13,16,17,19,20,22,23,25,32,32,34,35)

cens <- c(1,0,1,1,1,0,1,0,0,1,1,0,0,0,1,1,0,0,0,0,0)
```

```{r}

k <- seq(21,1)
len <- length(k)
Emp.h <- c()
Days <- time 
Cens <- cens

### The following cycles calculate all the data for the empirical risk, for ease of calculation the censored data are filled with zeros.


for(i in 1:len){
  
  if(Cens[i] == 0){
    
    Emp.h[i]= 0

    
  }else{
    
    Emp.h[i] = 1/k[i]

  }
  
}

cum.H <- cumsum(Emp.h)

for(i in 1:len){
  
  if(Cens[i] == 0){
    
    cum.H[i]= 0

  }
}


harzard.score<- as.data.frame(cbind(Days,Cens, k, Emp.h, cum.H))

head(round(harzard.score,3))
```
```{r}

### You must delete teh duplicated data

HAE <- subset(harzard.score, harzard.score$Cens != 0)
lme <- lm(HAE$Days[3:9] ~ HAE$cum.H[3:9])

HAW <- log(HAE)
lmw <- lm(HAW$Days[3:9]~HAW$cum.H[3:9])

HAL <- qnorm(1-exp(-HAE$cum.H[3:9]))
lml <- lm(HAW$Days[3:9]~HAL)

par(mfrow = c(1,3))

plot(HAE$cum.H[3:9],HAW$Days[3:9])
abline(lme)

plot(HAW$cum.H[3:9],HAW$Days[3:9])
abline(lmw)

plot(HAL,log(HAE$Days[3:9]))
abline(lml)

```
```{r}

st <- km.model$surv
tl <- km.model$time

km.model <- survfit(Surv(time,cens)~1)

lognormal <- qnorm(st)

rcsi <- -log(lognormal)

plot(log(tl),rcsi)
```

