---
title: "Survival times of prostatic cancer"
output: html_notebook
---
```{r}
library(survival)
library(muhaz)
```


```{r}
prostatic <- read.csv("prostatic.csv", header = T, sep=",")
attach(prostatic);
head(prostatic)
```

```{r}
par(mfrow=c(1,2))
hist(time)
boxplot(time)
```

```{r}

treatment1 <- subset(prostatic, treatment == 1)

treatment2 <- subset(prostatic, treatment == 2)

```



```{r}
par(mfrow=c(2,2))

hist(treatment1$time)
boxplot(treatment1$time)


hist(treatment2$time)
boxplot(treatment2$time)

```

```{r}
un1 <- sort(unique(treatment1$time))
un2 <- sort(unique(treatment2$time))

len <- length(un1)


St1 <- c()

for ( i in 1:len){
  
  St1[i] <- sum(treatment1$time > un1[i])
  
}


St1 <- St1/len


len <- length(un2)


St2 <- c()

for ( i in 1:len){
  
  St2[i] <- sum(treatment2$time > un2[i])
  
}


St2 <- St2/len
```

```{r}
par(mfrow=c(1,2))

plot(un1,St1)
plot(un2,St2)
```


```{r}

rt0_1 <- sum(St1[-1])/St1[1]
rt0_2 <- sum(St1[-1])/St2[1]
cbind(rt0_1, rt0_2)


```

```{r}
rt1 <- c()


for ( i in 1:len){
  
  rt1[i] <- sum(St1[-1:-i])/St1[i]
  
}

rt2 <- c()


for ( i in 1:len){
  
  rt2[i] <- sum(St2[-1:-i])/St2[i]
  
}


cbind(rt1,rt2)
```


```{r}
riesgo.can <- muhaz(time,status, max.time = 70)
plot(riesgo.can)
```


```{r}
# Estimador K-M Grupos

ekm <- survfit(Surv(time,status)~treatment)
summary(ekm)
plot(ekm,lty=c(2,1),xlab="Tiempo (semanas)", ylab= "S(t) estimada")
legend(1,0.3,lty=c(2,1), c("treament1", "treament2"), lwd=1, bty="n")

```

```{r}

ekm1 <- survfit(Surv(treatment1$time,treatment1$status)~1)
summary(ekm1)
ekm2 <- survfit(Surv(treatment2$time,treatment2$status)~1)
summary(ekm2)
```


```{r}
par(mfrow=c(1,2))
plot(ekm1)
plot(ekm2)
```


```{r}
ena <- survfit(Surv(time,status)~treatment, type = "fh")
summary(ena)

plot(ena,lty=c(2,1),xlab="Tiempo (semanas)", ylab= "S(t) estimada")
legend(1,0.3,lty=c(2,1), c("treament1", "treament2"), lwd=1, bty="n")

```


```{r}
# Estimador NA Grupo de Control, Fleming and Harrington = fh

ena1 <- survfit(Surv(treatment1$time,treatment1$status)~1, type = "fh")
summary(ena1)

# Estimador NA Grupo de Eseroide, Fleming and Harrington = fh

ena2 <- survfit(Surv(treatment2$time,treatment2$status)~1, type = "fh")
summary(ena2)

```



```{r}

par(mfrow=c(1,2))
plot(ena1,xlab="Tiempo (semanas)", ylab= "S(t) estimada")
plot(ena2,xlab="Tiempo (semanas)", ylab= "S(t) estimada")
```


```{r}
index <- order(treatment1$time)
treatment1 <- treatment1[index,]

index <- order(treatment2$time)
treatment2 <- treatment2[index,]
```

```{r}
len <- length(treatment1$time)
i <- seq(1:len)
p_score1 <- 1- ((i-0.5)/len)
```

```{r}
len <- length(treatment2$time)
i <- seq(1:len)
p_score2 <- 1- ((i-0.5)/len)
```



```{r}
plot(treatment1$time, p_score1, col = "red", ylab= "Plotting position S(t)", xlab="Time",)
points(treatment2$time, p_score2, col = "blue")
legend("bottomleft", legend=c("Treatment 1", "Treatment 2"), col = c("red","blue"), pch = 19, bty = "n")
```


```{r}

par(mfrow=c(1,3))

plot(log(treatment1$time), log(-1*log(p_score1)), col = "red", ylab= "Plotting position S(t)", xlab="Time", main =" Weibull")

points(log(treatment2$time), log(-1*log(p_score2)), col = "blue")

legend("bottomleft", legend=c("Treatment 1", "Treatment 2"), col = c("red","blue"), pch = 19, bty = "n")


plot(log(treatment1$time), -1*log(p_score1), col = "red", ylab= "Plotting position S(t)", xlab="Time", main =" exponential")

points(log(treatment2$time), -1*log(p_score2), col = "blue")

legend("bottomleft", legend=c("Treatment 1", "Treatment 2"), col = c("red","blue"), pch = 19, bty = "n")


plot(log(treatment1$time), qnorm(p_score1), col = "red", ylab= "Plotting position S(t)", xlab="Time", main =" Lognormal")

points(log(treatment2$time), qnorm(p_score2), col = "blue")

legend("bottomleft", legend=c("Treatment 1", "Treatment 2"), col = c("red","blue"), pch = 19, bty = "n")
```


```{r}

logT1 <- log(ekm1$time)
logT2 <- log(ekm2$time)

logLogSurv1 <- log(-log(ekm1$surv))
logSurv1 <- -log(ekm1$surv)
qnormSurv1 <- qnorm(ekm1$surv)


logLogSurv2 <- log(-log(ekm2$surv))
logSurv2 <- -log(ekm2$surv)
qnormSurv2 <- qnorm(ekm2$surv)

```

```{r}


plot(log(ekm1$time), log(-1*log(ekm1$surv)), col = "red", ylab= "Plotting position S(t)", xlab="Time", main =" Weibull",ylim= c(-5,5))

points(log(treatment1$time), log(-1*log(p_score1)), col = "blue")

legend("bottomleft", legend=c("ekm", "empirical"), col = c("red","blue"), pch = 19, bty = "n")

```

```{r}
logrank <- survdiff(Surv(time,status)~ treatment)
logrank
```

### cox

```{r}
cox <- coxph(Surv(time,status) ~ tomour)
summary(cox)
```
```{r}
cox1 <- coxph(Surv(time,status) ~ tomour + haem)
summary(cox1)
```
```{r}
cox2 <- coxph(Surv(time,status) ~ tomour + haem +gleason)
summary(cox2)
```


```{r}
cox3 <- coxph(Surv(time,status) ~ tomour + haem + gleason +age)
summary(cox3)
```
```{r}
anova(cox, cox1, cox2, cox3, test = "LRT")
```

```{r}
cox4 <- coxph(Surv(time,status) ~ treatment + age)
summary(cox4)
```


```{r}

plot(predict(cox4), residuals(cox4),
     xlab= "Fitted values", ylab ="Martingale residuals",
     main="residual Plot", las = 1)
### add a line ax y = residual = 0

# fir a smoother thru the points

lines(smooth.spline(predict(cox4), residuals(cox4)), col = "red")
```
```{r}

k <- residuals(cox4,type="martingale")


cox.zph(cox3,transform="rank")

```

```{r}
plot(cox.zph(cox4,transform="identity"))
```

```{r}

plot(k~age)
```

